server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    host: 192.168.43.34
    username: chenxm
    password: chenxm
    virtual-host: /leyou
  redis:
    host: 192.168.43.34
ly:
  sms:
    accessKeyId: XXXX     #短信服务的accessKeyId
    accessKeySecret: xxx    #短信服务的accessKeySecret
    signName: xxx商城       #签名名称
    verifyCodeTemplate: SMS_XXXX     #模板名称