server:
  port: 8084
spring:
  application:
    name: page-service
  thymeleaf:
    cache: false
  rabbitmq:
    host: 192.168.43.34
    username: chenxm
    password: chenxm
    virtual-host: /leyou
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10000/eureka